# Development overrides for Docker Compose
services:
  llm-api:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - RELOAD=true
    volumes:
      - ./models:/app/models
      - ./frontend:/app/frontend
      - .:/app  # Mount source code for development
    command: ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
