# Production overrides - use with: docker compose -f docker-compose.yml -f docker-compose.prod.yml up
services:
  llm-api:
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - API_WORKERS=${API_WORKERS:-2}
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-12G}
          cpus: '6.0'
        reservations:
          memory: ${MEMORY_RESERVATION:-8G}
          cpus: '4.0'
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-1}
              capabilities: [gpu]
      replicas: 1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 120s
    # Production security hardening
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: "1000:1000"

  redis:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    # Don't expose Redis port in production
    ports: []
    healthcheck:
      interval: 60s
      timeout: 10s
      retries: 5
    cap_drop:
      - ALL
    user: "999:999"
    